object frmAtualizaDB: TfrmAtualizaDB
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmAtualizaDB'
  ClientHeight = 93
  ClientWidth = 572
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object pnl1: TPanel
    Left = 0
    Top = 0
    Width = 572
    Height = 93
    Align = alClient
    BevelOuter = bvLowered
    BevelWidth = 3
    BorderWidth = 3
    Color = clBlack
    ParentBackground = False
    TabOrder = 0
    object pnl2: TPanel
      Left = 6
      Top = 6
      Width = 560
      Height = 81
      Align = alClient
      BevelOuter = bvNone
      Color = 16776176
      Enabled = False
      ParentBackground = False
      TabOrder = 0
      object lbl1: TLabel
        Left = 16
        Top = 24
        Width = 405
        Height = 87
        Caption = 'ATUALIZANDO O BANCO DE DADOS...'#13#10#13#10
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object Label1: TLabel
        Left = 448
        Top = 24
        Width = 104
        Height = 29
        Caption = 'AGUARDE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
    end
  end
end
